export const GET_ASSET_DETAIL_REQUEST = "GET_ASSET_DETAIL_REQUEST"
export const GET_ASSET_DETAIL_SUCCESS = "GET_ASSET_DETAIL_SUCCESS"
export const GET_ASSET_DETAIL_FAILURE = "GET_ASSET_DETAIL_FAILURE"



export const GET_ALL_ASSETS_REQUEST = "GET_ALL_ASSETS_REQUEST"
export const GET_ALL_ASSETS_SUCCESS = "GET_ALL_ASSETS_SUCCESS"
export const GET_ALL_ASSETS_FAILURE = "GET_ALL_ASSETS_FAILURE"