export const GET_CURENT_CREATIVE_USER_REQUEST = "GET_CURENT_CREATIVE_USER_REQUEST";
export const GET_CURENT_CREATIVE_USER_SUCCESS = "GET_CURENT_CREATIVE_USER_SUCCESS";
export const GET_CURENT_CREATIVE_USER_FAILURE = "GET_CURENT_CREATIVE_USER_FAILURE";



export const SET_EXPERTISE_REQUEST = "SET_EXPERTISE_REQUEST"
export const SET_EXPERTISE_SUCCESS = "SET_EXPERTISE_SUCCESS"
export const SET_EXPERTISE_FAILURE = "SET_EXPERTISE_FAILURE"

export const SET_EXPERIENCE_REQUEST = "SET_EXPERIENCE_REQUEST"
export const SET_EXPERIENCE_SUCCESS = "SET_EXPERIENCE_SUCCESS"
export const SET_EXPERIENCE_FAILURE = "SET_EXPERIENCE_FAILURE"

export const SET_DESCRIPTION_REQUEST = "SET_DESCRIPTION_REQUEST"
export const SET_DESCRIPTION_SUCCESS = "SET_DESCRIPTION_SUCCESS"
export const SET_DESCRIPTION_FAILURE = "SET_DESCRIPTION_FAILURE"

export const UPLOAD_CV_REQUEST = "UPLOAD_CV_REQUEST"
export const UPLOAD_CV_SUCCESS = "UPLOAD_CV_SUCCESS"
export const UPLOAD_CV_FAILURE = "UPLOAD_CV_FAILURE"

export const UPLOAD_PAST_JOB_IMAGE_REQUEST = "UPLOAD_PAST_JOB_IMAGE_REQUEST"
export const UPLOAD_PAST_JOB_IMAGE_SUCCESS = "UPLOAD_PAST_JOB_IMAGE_SUCCESS"
export const UPLOAD_PAST_JOB_IMAGE_FAILURE = "UPLOAD_PAST_JOB_IMAGE_FAILURE"




export const POST_PAST_EDUCATION_REQUEST = "POST_PAST_EDUCATION_REQUEST"
export const POST_PAST_EDUCATION_SUCCESS = "POST_PAST_EDUCATION_SUCCESS"
export const POST_PAST_EDUCATION_FAILURE = "POST_PAST_EDUCATION_FAILURE"



export const POST_PAST_EMPLOYMENT_REQUEST = "POST_PAST_EMPLOYMENT_REQUEST"
export const POST_PAST_EMPLOYMENT_SUCCESS = "POST_PAST_EMPLOYMENT_SUCCESS"
export const POST_PAST_EMPLOYMENT_FAILURE = "POST_PAST_EMPLOYMENT_FAILURE"


export const SET_IMAGE_REQUEST = "SET_IMAGE_REQUEST"
export const SET_IMAGE_SUCCESS = "SET_IMAGE_SUCCESS"
export const SET_IMAGE_FAILURE = "SET_IMAGE_FAILURE"


export const CURRENT_CREATIVE_USER_RESET = "CUR_CREATIVE_USER_RESET"