export const GET_ALL_PENDING_REQUEST = "GET_ALL_PENDING_REQUEST"
export const GET_ALL_PENDING_SUCCESS = "GET_ALL_PENDING_SUCCESS"
export const GET_ALL_PENDING_FAILURE = "GET_ALL_PENDING_FAILURE"



export const GET_ALL_COMPLETED_REQUEST = "GET_ALL_COMPLETED_REQUEST"
export const GET_ALL_COMPLETED_SUCCESS = "GET_ALL_COMPLETED_SUCCESS"
export const GET_ALL_COMPLETED_FAILURE = "GET_ALL_COMPLETED_FAILURE"


export const GET_ALL_APPLICATION_ACCEPTED_REQUEST = "GET_ALL_APPLICATION_ACCEPTED_REQUEST"
export const GET_ALL_APPLICATION_ACCEPTED_SUCCESS = "GET_ALL_APPLICATION_ACCEPTED_SUCCESS"
export const GET_ALL_APPLICATION_ACCEPTED_FAILURE = "GET_ALL_APPLICATION_ACCEPTED_FAILURE"
