export const GET_CURENT_USER_JOBS_REQUEST = "GET_CURENT_USER_JOBS_REQUEST";
export const GET_CURENT_USER_JOBS_SUCCESS = "GET_CURENT_USER_JOBS_SUCCESS";
export const GET_CURENT_USER_JOBS_FAILURE = "GET_CURENT_USER_JOBS_FAILURE";



//Delete request
export const DELETE_CURENT_USER_JOB_REQUEST ="DELETE_CURENT_USER_JOB_REQUEST";
export const DELETE_CURENT_USER_JOB_SUCCESS ="DELETE_CURENT_USER_JOB_SUCCESS";
export const DELETE_CURENT_USER_JOB_FAILURE ="DELETE_CURENT_USER_JOB_FAILURE";


//UPDATE REQUEST
export const UPDATE_CURENT_USER_JOB_REQUEST ="UPDATE_CURENT_USER_JOB_REQUEST";
export const UPDATE_CURENT_USER_JOB_SUCCESS ="UPDATE_CURENT_USER_JOB_SUCCESS";
export const UPDATE_CURENT_USER_JOB_FAILURE ="UPDATE_CURENT_USER_JOB_FAILURE";

export const RESET_CURRENT_JOB_DATA = "RESET_CURRENT_JOB_DATA";




export const GET_CURENT_USER_JOBS_APPLIED_CONFIRMED_REQ_REQUEST = "GET_CURENT_USER_JOBS_APPLIED_CONFIRMED_REQ_REQUEST";
export const GET_CURENT_USER_JOBS_APPLIED_CONFIRMED_REQ_SUCCESS = "GET_CURENT_USER_JOBS_APPLIED_CONFIRMED_REQ_SUCCESS";
export const GET_CURENT_USER_JOBS_APPLIED_CONFIRMED_REQ_FAILURE = "GET_CURENT_USER_JOBS_APPLIED_CONFIRMED_REQ_FAILURE";

export const GET_CURENT_USER_JOBS_COMPLETE_REQUEST = "GET_CURENT_USER_JOBS_COMPLETE_REQUEST";
export const GET_CURENT_USER_JOBS_COMPLETE_SUCCESS = "GET_CURENT_USER_JOBS_COMPLETE_SUCCESS";
export const GET_CURENT_USER_JOBS_COMPLETE_FAILURE = "GET_CURENT_USER_JOBS_COMPLETE_FAILURE";



export const GET_CURENT_USER_JOBS_PENDING_REQUEST = "GET_CURENT_USER_JOBS_PENDING_REQUEST";
export const GET_CURENT_USER_JOBS_PENDING_SUCCESS = "GET_CURENT_USER_JOBS_PENDING_SUCCESS";
export const GET_CURENT_USER_JOBS_PENDING_FAILURE = "GET_CURENT_USER_JOBS_PENDING_FAILURE";



export const SEARCH_JOB = "SEARCH_JOB"
export const PAGINATE_JOBS = "PAGINATE_JOBS"
export const FILTER_JOBS = "FILTER_JOBS"

