//GET REQUEST
export const GET_ESTIMATE_JOB_REQUEST ="GET_ESTIMATE_JOB_REQUEST";
export const GET_ESTIMATE_JOB_SUCCESS ="GET_ESTIMATE_JOB_SUCCESS";
export const GET_ESTIMATE_JOB_FAILURE ="GET_ESTIMATE_JOB_FAILURE";

//RESET
export const ESTIMATE_JOB_RESET = "ESTIMATE_JOB_RESET";


//Post request
export const POST_ESTIMATE_JOB_REQUEST ="POST_ESTIMATE_JOB_REQUEST";
export const POST_ESTIMATE_JOB_SUCCESS ="POST_ESTIMATE_JOB_SUCCESS";
export const POST_ESTIMATE_JOB_FAILURE ="POST_ESTIMATE_JOB_FAILURE";

//Delete request
export const DELETE_ESTIMATE_JOB_REQUEST ="DELETE_ESTIMATE_JOB_REQUEST";
export const DELETE_ESTIMATE_JOB_SUCCESS ="DELETE_ESTIMATE_JOB_SUCCESS";
export const DELETE_ESTIMATE_JOB_FAILURE ="DELETE_ESTIMATE_JOB_FAILURE";


//UPDATE REQUEST
export const UPDATE_ESTIMATE_JOB_REQUEST ="UPDATE_ESTIMATE_JOB_REQUEST";
export const UPDATE_ESTIMATE_JOB_SUCCESS ="UPDATE_ESTIMATE_JOB_SUCCESS";
export const UPDATE_ESTIMATE_JOB_FAILURE ="UPDATE_ESTIMATE_JOB_FAILURE";