//GET REQUEST
export const GET_JOB_REQUEST ="GET_JOB_REQUEST";
export const GET_JOB_SUCCESS ="GET_JOB_SUCCESS";
export const GET_JOB_FAILURE ="GET_JOB_FAILURE";

//RESET
export const JOB_RESET = "JOB_RESET";


//Post request
export const POST_JOB_REQUEST ="POST_JOB_REQUEST";
export const POST_JOB_SUCCESS ="POST_JOB_SUCCESS";
export const POST_JOB_FAILURE ="POST_JOB_FAILURE";

//Delete request
export const DELETE_JOB_REQUEST ="DELETE_JOB_REQUEST";
export const DELETE_JOB_SUCCESS ="DELETE_JOB_SUCCESS";
export const DELETE_JOB_FAILURE ="DELETE_JOB_FAILURE";


//UPDATE REQUEST
export const UPDATE_JOB_REQUEST ="UPDATE_JOB_REQUEST";
export const UPDATE_JOB_SUCCESS ="UPDATE_JOB_SUCCESS";
export const UPDATE_JOB_FAILURE ="UPDATE_JOB_FAILURE";

//Like job

export const LIKE_JOB_REQUEST ="LIKE_JOB_REQUEST";
export const LIKE_JOB_SUCCESS ="LIKE_JOB_SUCCESS";
export const LIKE_JOB_FAILURE ="LIKE_JOB_FAILURE";

//dislike job

export const DISLIKE_JOB_REQUEST ="DISLIKE_JOB_REQUEST";
export const DISLIKE_JOB_SUCCESS ="DISLIKE_JOB_SUCCESS";
export const DISLIKE_JOB_FAILURE ="DISLIKE_JOB_FAILURE";

//Rate job

export const RATE_JOB_REQUEST ="RATE_JOB_REQUEST";
export const RATE_JOB_SUCCESS ="RATE_JOB_SUCCESS";
export const RATE_JOB_FAILURE ="RATE_JOB_FAILURE";



//Apply job

export const APPLY_JOB_REQUEST ="APPLY_JOB_REQUEST";
export const APPLY_JOB_SUCCESS ="APPLY_JOB_SUCCESS";
export const APPLY_JOB_FAILURE ="APPLY_JOB_FAILURE";