export const USER_JOB_STATISTICS_REQUEST = "USER_JOB_STATISTICS_REQUEST";
export const USER_JOB_STATISTICS_SUCCESS = "USER_JOB_STATISTICS_SUCCESS";
export const USER_JOB_STATISTICS_FAILURE = "USER_JOB_STATISTICS_FAILURE";
