export const tags =[
    'Developer',
    'photography',
    'Event Planning',
    'Photoraphy',
    'Python',
    'Javascript',
    'java',
    '.net',
    'php',
    'django',
    'flask',
    'laravel',
    'flutter',
    'android',
    'angular',
    'react',
    'vue',
    'full stack',
    'frontend',
    'backend',
    'dart',
    'mobile app',
    'desktop app',
    'electron',
    'golang',
    'food photography',
    'css',
    'html',
    'bootstrap',
    'Tailwind',
    'codeigniter',
    "Potrait Photography",
    "Event Photography",
    "Food photography",
    "Documentary photography",
    "Wedding photography",
    "Videography",
    "Aeriel Photography",
    'Wedding planning',
    'ui/ux design',
    'mobile app',
    'mobile design',
    'enterprice',
    'finance',
    'commercial',
    
    
]