name: justclick staging deployment

on:
  push:
    branches: [staging]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: SCP to server
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.HOST}}
          username: ${{ secrets.USER }}
          port: ${{ secrets.PORT }}
          password: ${{ secrets.PASSWORD }}
          source: "."
          target: "justclick"

      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          script: |
            cd justclick
            npm install
            export NODE_OPTIONS=--max_old_space_size=4096
            npm run build --if-present
            sudo cp -r build/* /var/www/html/justclick
            sudo systemctl restart nginx